services:
  mongodb:
    image: mongo:6.0.8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker-compose/data/mongo:/data/db
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: userAdmin
      MONGO_INITDB_ROOT_PASSWORD: userPassword
      MONGO_INITDB_DATABASE: todoapp
  todo-app-backend:
    container_name: todoapp_backend
    build:
      context: backend/.
      args:
        TODO_APP_BACKEND_PORT: 8080
    restart: always
    ports:
      - 8080:8080
