services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker-compose/data/mongo:/data/db
      - ./docker-compose/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      MONGO_INITDB_DATABASE: todoapp
    command: [--auth]
  todo-app-backend:
    container_name: todoapp_backend
    build:
      context: backend/.
      args:
        TODO_APP_BACKEND_PORT: 4444
    restart: always
    ports:
      - 4444:4444
